# Generated by Django 3.2.4 on 2021-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter city name', max_length=50)),
                ('zip_code', models.PositiveIntegerField(help_text="enter your city's zip code")),
            ],
        ),
    ]
